### ISSUE TITLE
[FEATURE REQUEST]

### ISSUE THREAD

**Issue by jackgraddon** [garagepoort/StaffPlusPlus#121]
It would be nice to have a support ticket command, such as `/ticket create (ticket description)`. That would be a lot nicer than using the report command for support tickets, and I cannot seem to find any commands for support tickets, which Staff+ did have if I recall.

**Comment by garagepoort** [comment]
Hi @jackgraddon ,
Thanks for the feature request. The ticketing system was removed because it was bugged out in the original Staff+ plugin.

I did not add it again because I thought having the reporting system would be enough.
Should other people feel the same about having this feature I can add it again.

Maybe we can have a discussion about this on the discord channel

**Comment by garagepoort** [comment]
Closed due to inactivity
