### ISSUE TITLE
GUI Rework Suggestions/Discussion

### ISSUE THREAD

**Issue by Nutmegan** [garagepoort/StaffPlusPlus#177]
This feature request is more of a collection of user suggestions to consider when/if an entire GUI rework ever comes to the table. Most of the suggestions involve removing almost everything that is currently in the hot bar, either completely, or moving into deeper GUI levels. The end result leaves the HOT BAR with only 5 used slots, freeing up slots for me to add things like an inspector wand from CoreProtect and other plugin tools my admins use. Hope these suggestions will be useful and maybe spark some discussion. 

1. I like the current STAFF option, but it’s so limiting. I’d rather see PLAYERS and have that open a GUI for deeper filtering. STAFF would move to this filtering menu along with these possible options: PLAYERS, STAFF, MINERS, BANS, MUTES, etc…

- Each of these options then opens a deeper GUI option with relevant details. So for instance PLAYERS could have a list of player heads that can be hovered over for more details (customizable and shown as lore)(and sorted by ONLINE/OFFLINE). Default details might be the players: NAME:RANK, IP, WORLD:LOCATION, HRS PLAYED, etc….

- Clicking on a specific player head could open a player specific GUI. This would be where most of the current Hot Bar tools (TeleportTo, TeleportHere, Enderchest, CPS, Freeze, Follow, Examine?) could move to along with new tools such as Protect Player. Allowing admins to preform those actions on that player. This could also house actions like viewing a players infraction history or current reports, etc.

- Finally, one additional NEW tool could be added to the hot bar that would be a player selector wand. This wand would maintain the old functionality of clicking on a player in game and preforming the action of opening that player GUI mentioned above. From there the staff member could then select further actions (the old actions) to preform on the player.

2. HUB GUI: There have been some good changes here, but there are a lot of new modules that aren’t reflected here and still exist only by commands. This should be a menu for all those BAN, MUTE, REPORT, INVESTIGATIONS, etc… that then have their own GUI that expands from this menu.

3. VANISH: Does the On/Off indicator still work on this? The new GLOW INK would be a great on/off indicator for this.

4. CHEST INSPECTOR: so admins can still open/check chests. (EDIT this is currently called EXAMINE and is a chest icon)

5. RANDOM TELEPORT: Meh, keep or remove, I don’t really use it, but we can remove it from our end.

6. REMOVE: Compass/Launcher since we can already fly and most people have elytra/rockets. At the very least change the icon to a rocket or an elytra.

7. MOVE Enderchest, CPS, Freeze, Follow, Examine to the PLAYER GUI (see above)

**Comment by garagepoort** [comment]
Hey @Nutmegan 

Thanks for the suggestion. It actually comes at a perfect time since I am reworking the code to allow for easier GUI development.

1. I like the idea of the player GUI and will definitely implement that in one of the upcoming releases. 

2. For the HUB, yeah I haven't added everything in it yet, need to update.

3. No idea if the vanish indicator still works, I do like the idea of using the glow ink on newer mc versions

4. Not sure what this would exactly do? Staff members can still open chests while in staff mode?

5. Won't remove as I don't want to break existing functionality for the current users.

6.  Won't remove as I don't want to break existing functionality for the current users. But will change the icon.

7. These things will also be available in the player GUI but I'm not sure about removing them. I think I'll keep them but disabled them by default. Just don't want to remove stuff as I do claim that staff++ holds all staff+ features.

Would be nice if some other people could shine some light on this.
It might be a good idea to also share this in the Staff++ discord #feature-requests channel

**Comment by Nutmegan** [comment]
4. Sorry, it's currently called EXAMINE it is a chest icon
5. - 7. Understandable as long as we still have the option to remove them to our personal preferences I don't think it's an issue

I would be happy to make a post on Discord, I just didn't want to open a can of worms for you. After all, you're already working on a lot. 

I put together a visual, all hypothetical of course.
<img width="760" alt="Screen Shot 2021-08-13 at 10 29 31 AM" src="https://user-images.githubusercontent.com/9382508/129391138-f2940303-0e25-4eb9-9359-e19884732816.png">

**Comment by garagepoort** [comment]
Thank you for the mockups. I'll release a first version of this with the next update.

**Comment by Nutmegan** [comment]
I don't really know how the GitHub process works... Do you need me to do something to help you get this closed? Or are you still working on it? Just checking.

**Comment by garagepoort** [comment]
These GUIs have been added. Any improvements can be discussed in new tickets. Closing
